export const LOADING_SMURFS = 'LOADING_SMURFS';
export const GET_SMURFS_SUCESS = 'GET_SMURFS_SUCCESS';
export const GET_SMURFS_FAILURE = 'GET_SMURFS_FAILURE';
export const ADDING_SMURFS = 'ADDING_SMURFS';
export const ADD_SMURFS_SUCCESS = 'ADD_SMURFS_SUCCESS';
export const ADD_SMURFS_FAILURE = 'ADD_SMURFS_FAILURE';
export const UPDATING_SMURFS = 'UPDATING_SMURFS';
export const UPDATE_SMURFS_SUCCESS = 'UPDATE_SMURFS_SUCCESS';
export const UPDATE_SMURFS_FAILURE = 'UPDATE_SMURFS_FAILURE';
export const DELETING_SMURFS = 'UPDATING_SMURFS';
export const DELETE_SMURFS_SUCCESS = 'DELETE_SMURFS_SUCCESS';
export const DELETE_SMURFS_FAILURE = 'DELETE_SMURFS_FAILURE';




